version: "3"
services:
    my-app:
        image: alaetouba/node-mongodb-mongoexpress-image
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 3001:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - mongodb
